### ISSUE TITLE
Improvement: Add a log to the simulator output with details of commit, date, etc.

### ISSUE THREAD

**Issue by brunohcfaria** [Radio-Spectrum/SHARC#162]
Improvement: Add a log to the simulator output with details of commit, date, etc.

**Comment by artistrea** [comment]
Suggestion:

At Results, output right beside the parameter yaml a new `.yaml` file with content such as:

```yaml
repo:
    url: git@github.com:Radio-Spectrum/SHARC.git
    branch: development
    commit: 293036faf59dfa00cd0c9e2c0fb209be2d8d160d
run:
    started_at: 2025-06-26T10:41:55.071071
    command: /home/someone/projects/Radio-Spectrum/SHARC/.venv/bin/python /home/someone/some/folder/main_cli.py -p some/param.yaml
    python_verson: 3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0]
    pkgs:
    - area==1.1.1
    - asttokens==2.4.1
```
